apiVersion: v1
kind: Pod
metadata:
  name: yaml-pod
  labels:
    app: my-app
    environment: dev
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
