apiVersion: v1
kind: Service
metadata:
  name: simple-web-app-service
spec:
  selector:
    app: simple-web-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80          
      targetPort: 80     
      nodePort: 30007    
